// Map TBA country full names → ISO 3166-1 alpha-2 (lowercase, for flag-icons CSS)
// Covers every country FRC teams have come from in the last decade.
export const COUNTRY_TO_ISO = {
  "USA": "us",
  "Canada": "ca",
  "Mexico": "mx",
  "Brazil": "br",
  "Chile": "cl",
  "Colombia": "co",
  "Ecuador": "ec",
  "Dominican Republic": "do",
  "Israel": "il",
  "Turkey": "tr",
  "Türkiye": "tr",
  "China": "cn",
  "Chinese Taipei": "tw",
  "Taiwan": "tw",
  "Japan": "jp",
  "South Korea": "kr",
  "Korea, Republic of": "kr",
  "Korea": "kr",
  "India": "in",
  "Singapore": "sg",
  "Philippines": "ph",
  "Vietnam": "vn",
  "Indonesia": "id",
  "Thailand": "th",
  "Malaysia": "my",
  "Hong Kong": "hk",
  "Australia": "au",
  "New Zealand": "nz",
  "United Kingdom": "gb",
  "Great Britain": "gb",
  "England": "gb",
  "Scotland": "gb",
  "Wales": "gb",
  "Northern Ireland": "gb",
  "Ireland": "ie",
  "France": "fr",
  "Germany": "de",
  "Netherlands": "nl",
  "Belgium": "be",
  "Spain": "es",
  "Portugal": "pt",
  "Italy": "it",
  "Switzerland": "ch",
  "Austria": "at",
  "Sweden": "se",
  "Norway": "no",
  "Denmark": "dk",
  "Finland": "fi",
  "Iceland": "is",
  "Poland": "pl",
  "Czech Republic": "cz",
  "Czechia": "cz",
  "Hungary": "hu",
  "Romania": "ro",
  "Bulgaria": "bg",
  "Greece": "gr",
  "Russia": "ru",
  "Ukraine": "ua",
  "Belarus": "by",
  "Latvia": "lv",
  "Lithuania": "lt",
  "Estonia": "ee",
  "South Africa": "za",
  "Saudi Arabia": "sa",
  "United Arab Emirates": "ae",
  "Qatar": "qa",
  "Kuwait": "kw",
  "Bahrain": "bh",
  "Egypt": "eg",
  "Morocco": "ma",
  "Tunisia": "tn",
  "Kazakhstan": "kz",
  "Pakistan": "pk",
  "Bangladesh": "bd",
};

// US state full names → 2-letter postal codes (lowercase, for flag-icons us-XX)
export const STATE_TO_CODE = {
  "Alabama": "al", "Alaska": "ak", "Arizona": "az", "Arkansas": "ar",
  "California": "ca", "Colorado": "co", "Connecticut": "ct", "Delaware": "de",
  "Florida": "fl", "Georgia": "ga", "Hawaii": "hi", "Idaho": "id",
  "Illinois": "il", "Indiana": "in", "Iowa": "ia", "Kansas": "ks",
  "Kentucky": "ky", "Louisiana": "la", "Maine": "me", "Maryland": "md",
  "Massachusetts": "ma", "Michigan": "mi", "Minnesota": "mn", "Mississippi": "ms",
  "Missouri": "mo", "Montana": "mt", "Nebraska": "ne", "Nevada": "nv",
  "New Hampshire": "nh", "New Jersey": "nj", "New Mexico": "nm", "New York": "ny",
  "North Carolina": "nc", "North Dakota": "nd", "Ohio": "oh", "Oklahoma": "ok",
  "Oregon": "or", "Pennsylvania": "pa", "Rhode Island": "ri", "South Carolina": "sc",
  "South Dakota": "sd", "Tennessee": "tn", "Texas": "tx", "Utah": "ut",
  "Vermont": "vt", "Virginia": "va", "Washington": "wa", "West Virginia": "wv",
  "Wisconsin": "wi", "Wyoming": "wy",
  "District of Columbia": "dc",
  "Puerto Rico": "pr",
};

// Resolve a team's flag info: prefer US state for US teams, else country.
// Returns { kind: 'state'|'country'|null, code, label }.
export function resolveFlag(country, state_prov) {
  if (country === "USA" && state_prov && STATE_TO_CODE[state_prov]) {
    return { kind: "state", code: STATE_TO_CODE[state_prov], label: state_prov };
  }
  if (country && COUNTRY_TO_ISO[country]) {
    return { kind: "country", code: COUNTRY_TO_ISO[country], label: country };
  }
  return { kind: null, code: null, label: country || state_prov || "Unknown" };
}
